### ISSUE TITLE
Pre-deployment - სამუშაოები

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-d8#125]
# აუცილებელი
- [x] Paginator - ის გასწორება - https://github.com/Girchi/girchi-com-d8/pull/123;
- [x] Frozen ბლოკების ჩასმა მთავარ გვერდზე - https://github.com/Girchi/girchi-com-d8/issues/89
- [x] მარჯინების გატესტვა: https://github.com/Girchi/girchi-com-d8/issues/76
- [x] Masquerade ვიჯეტის გათიშვა https://github.com/Girchi/girchi-com-d8/issues/97

# თუ მოესწრება კარგია
- [x] Facebook კომენტარების ჩართვა: https://github.com/Girchi/girchi-com-d8/issues/108
